
server:
  port: 2001

# 配置注册中心
eureka:
  client:
    service-url:
      defaultZone: http://xjf:123456@localhost:8761/eureka/,http://xjf:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

# 路由配置，加两个 * 号，代表多级匹配
spring:
  application:
    name: springcloud-gateway-demo
  cloud:
    gateway:
      # 路由配置
      routes:
      - id: path_route
        uri: http://xjf666.xyz
        predicates:
        - Path=/course/**
      - id: user-service
        # 服务名称区分大小写
        uri: lb://eureka-client-user-service
        predicates:
        - Path=/ecus/**
        filters:
        # 转发请求时去掉1级前缀
        - StripPrefix=1
      discovery:
        locator:
          # 开启自动转发 Eureka 中注册的服务
          enabled: true
          # 服务名称区分大小写(只能二选一)，此处使用小写
          lower-case-service-id: true
