server:
  port: 2001

# \u8DEF\u7531\u914D\u7F6E\uFF0C\u52A0\u4E24\u4E2A * \u53F7\uFF0C\u4EE3\u8868\u591A\u7EA7\u5339\u914D
spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://xjf666.xyz
          predicates:
          - Path=/course/**